// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";

export class CreateWithTimestamps {
  static encode(message: CreateWithTimestamps, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.trxHash);

    writer.uint32(16);
    writer.int64(message.startTime);

    writer.uint32(24);
    writer.int64(message.cliffTime);

    writer.uint32(32);
    writer.int64(message.endTime);

    writer.uint32(40);
    writer.uint64(message.depositedAmount);

    writer.uint32(48);
    writer.bool(message.isCancelable);

    writer.uint32(58);
    writer.string(message.acctSender);

    writer.uint32(66);
    writer.string(message.acctMint);

    writer.uint32(74);
    writer.string(message.acctSenderAta);

    writer.uint32(82);
    writer.string(message.acctRecipient);

    writer.uint32(90);
    writer.string(message.acctRecipientAta);

    writer.uint32(98);
    writer.string(message.acctTreasuryPda);

    writer.uint32(106);
    writer.string(message.acctTreasuryAta);

    writer.uint32(114);
    writer.string(message.acctStream);

    writer.uint32(122);
    writer.string(message.acctTokenProgram);
  }

  static decode(reader: Reader, length: i32): CreateWithTimestamps {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new CreateWithTimestamps();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.trxHash = reader.string();
          break;

        case 2:
          message.startTime = reader.int64();
          break;

        case 3:
          message.cliffTime = reader.int64();
          break;

        case 4:
          message.endTime = reader.int64();
          break;

        case 5:
          message.depositedAmount = reader.uint64();
          break;

        case 6:
          message.isCancelable = reader.bool();
          break;

        case 7:
          message.acctSender = reader.string();
          break;

        case 8:
          message.acctMint = reader.string();
          break;

        case 9:
          message.acctSenderAta = reader.string();
          break;

        case 10:
          message.acctRecipient = reader.string();
          break;

        case 11:
          message.acctRecipientAta = reader.string();
          break;

        case 12:
          message.acctTreasuryPda = reader.string();
          break;

        case 13:
          message.acctTreasuryAta = reader.string();
          break;

        case 14:
          message.acctStream = reader.string();
          break;

        case 15:
          message.acctTokenProgram = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  trxHash: string;
  startTime: i64;
  cliffTime: i64;
  endTime: i64;
  depositedAmount: u64;
  isCancelable: bool;
  acctSender: string;
  acctMint: string;
  acctSenderAta: string;
  acctRecipient: string;
  acctRecipientAta: string;
  acctTreasuryPda: string;
  acctTreasuryAta: string;
  acctStream: string;
  acctTokenProgram: string;

  constructor(
    trxHash: string = "",
    startTime: i64 = 0,
    cliffTime: i64 = 0,
    endTime: i64 = 0,
    depositedAmount: u64 = 0,
    isCancelable: bool = false,
    acctSender: string = "",
    acctMint: string = "",
    acctSenderAta: string = "",
    acctRecipient: string = "",
    acctRecipientAta: string = "",
    acctTreasuryPda: string = "",
    acctTreasuryAta: string = "",
    acctStream: string = "",
    acctTokenProgram: string = ""
  ) {
    this.trxHash = trxHash;
    this.startTime = startTime;
    this.cliffTime = cliffTime;
    this.endTime = endTime;
    this.depositedAmount = depositedAmount;
    this.isCancelable = isCancelable;
    this.acctSender = acctSender;
    this.acctMint = acctMint;
    this.acctSenderAta = acctSenderAta;
    this.acctRecipient = acctRecipient;
    this.acctRecipientAta = acctRecipientAta;
    this.acctTreasuryPda = acctTreasuryPda;
    this.acctTreasuryAta = acctTreasuryAta;
    this.acctStream = acctStream;
    this.acctTokenProgram = acctTokenProgram;
  }
}
