// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";
import { Cancel } from "./Cancel";
import { CreateWithTimestamps } from "./CreateWithTimestamps";
import { Initialize } from "./Initialize";
import { Renounce } from "./Renounce";
import { Withdraw } from "./Withdraw";
import { WithdrawMax } from "./WithdrawMax";

export class Data {
  static encode(message: Data, writer: Writer): void {
    const cancelList = message.cancelList;
    for (let i: i32 = 0; i < cancelList.length; ++i) {
      writer.uint32(10);
      writer.fork();
      Cancel.encode(cancelList[i], writer);
      writer.ldelim();
    }

    const createWithTimestampsList = message.createWithTimestampsList;
    for (let i: i32 = 0; i < createWithTimestampsList.length; ++i) {
      writer.uint32(18);
      writer.fork();
      CreateWithTimestamps.encode(createWithTimestampsList[i], writer);
      writer.ldelim();
    }

    const initializeList = message.initializeList;
    for (let i: i32 = 0; i < initializeList.length; ++i) {
      writer.uint32(26);
      writer.fork();
      Initialize.encode(initializeList[i], writer);
      writer.ldelim();
    }

    const renounceList = message.renounceList;
    for (let i: i32 = 0; i < renounceList.length; ++i) {
      writer.uint32(34);
      writer.fork();
      Renounce.encode(renounceList[i], writer);
      writer.ldelim();
    }

    const withdrawList = message.withdrawList;
    for (let i: i32 = 0; i < withdrawList.length; ++i) {
      writer.uint32(42);
      writer.fork();
      Withdraw.encode(withdrawList[i], writer);
      writer.ldelim();
    }

    const withdrawMaxList = message.withdrawMaxList;
    for (let i: i32 = 0; i < withdrawMaxList.length; ++i) {
      writer.uint32(50);
      writer.fork();
      WithdrawMax.encode(withdrawMaxList[i], writer);
      writer.ldelim();
    }

    writer.uint32(56);
    writer.uint64(message.blockNumber);

    writer.uint32(64);
    writer.int64(message.blockTimestamp);
  }

  static decode(reader: Reader, length: i32): Data {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Data();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.cancelList.push(Cancel.decode(reader, reader.uint32()));
          break;

        case 2:
          message.createWithTimestampsList.push(
            CreateWithTimestamps.decode(reader, reader.uint32())
          );
          break;

        case 3:
          message.initializeList.push(
            Initialize.decode(reader, reader.uint32())
          );
          break;

        case 4:
          message.renounceList.push(Renounce.decode(reader, reader.uint32()));
          break;

        case 5:
          message.withdrawList.push(Withdraw.decode(reader, reader.uint32()));
          break;

        case 6:
          message.withdrawMaxList.push(
            WithdrawMax.decode(reader, reader.uint32())
          );
          break;

        case 7:
          message.blockNumber = reader.uint64();
          break;

        case 8:
          message.blockTimestamp = reader.int64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  cancelList: Array<Cancel>;
  createWithTimestampsList: Array<CreateWithTimestamps>;
  initializeList: Array<Initialize>;
  renounceList: Array<Renounce>;
  withdrawList: Array<Withdraw>;
  withdrawMaxList: Array<WithdrawMax>;
  blockNumber: u64;
  blockTimestamp: i64;

  constructor(
    cancelList: Array<Cancel> = [],
    createWithTimestampsList: Array<CreateWithTimestamps> = [],
    initializeList: Array<Initialize> = [],
    renounceList: Array<Renounce> = [],
    withdrawList: Array<Withdraw> = [],
    withdrawMaxList: Array<WithdrawMax> = [],
    blockNumber: u64 = 0,
    blockTimestamp: i64 = 0
  ) {
    this.cancelList = cancelList;
    this.createWithTimestampsList = createWithTimestampsList;
    this.initializeList = initializeList;
    this.renounceList = renounceList;
    this.withdrawList = withdrawList;
    this.withdrawMaxList = withdrawMaxList;
    this.blockNumber = blockNumber;
    this.blockTimestamp = blockTimestamp;
  }
}
